spring:
  application:
    name: recommendationservice

  data:
    mongodb:
      url: mongodb://localhost:27018/fitnessrecommendation
      database: fitnessrecommendation

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/
