spring:
  application:
    name: userservice

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:9001/user
    username: postgres
    password: postgres

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/

